apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: podinfo
spec:
  interval: 5m
  url: https://gaurav-garv4u.github.io/podinfo-repo/
  #url: https://stefanprodan.github.io/podinfo
